language: python
python:
  - "2.7"

addons:
  postgresql: "9.3"

# command to install dependencies
install: "pip install -r requirements.txt"
install: "pip install -r requirements_dev.txt"

# command to run tests
script: python manage.py test

