language: python
addons:
  postgresql: "9.3"
python:
  - 2.7
install:
  - pip install -r askari/requirements.txt
  - pip install -r askari/requirements_dev.txt
before_script:
  - psql -c 'create database askari_example;' -U postgres
  - cp askari/local_settings.py.example askari/local_settings.py
  - sed -i -e 's/getpass\.getuser()/\"postgres\"/g' askari/local_settings.py
  - python manage.py syncdb --migrate --noinput --settings=askari.local_settings
script:
  - python manage.py test askari --settings=askari.local_settings


