language: python
services:
  - postgresql
python:
  - 2.7
install:
  - pip install -r askari/requirements.txt
  - pip install -r askari/requirements_dev.txt
  - pip install coveralls
before_script:
  - psql -c 'create database askari_development;' -U postgres
  - python manage.py syncdb --migrate --noinput
script:
  - coverage run --source=askari manage.py test
  - python manage.py test askari
after_success:
  - coveralls


